apiVersion: batch/v1
kind: Job
metadata:
  name: throw-dice-job
spec:
  template:
    spec:
      containers:
        - image: kodekloud/throw-dice
          name: throw-dice-job
      restartPolicy: OnFailure
  backoffLimit: 25
  completions: 3
