#PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
spec:
  accessModes:
    - ReadWriteOnce
#    - ReadOnlyMany
#    - ReadWriteMany
  capacity:
    storage: 1Gi
  
  awsElasticBlockStore:
    volumeID: <volume=id>
    fsType: ext4




#PersistentVolume
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-log
# spec:
#   accessModes:
#     - ReadWriteMany
#   capacity:
#     storage: 100Mi
#   hostPath:
#     path: /pv/log
#   persistentVolumeReclaimPolicy: Retain