apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
  namespace: default
spec:
#  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

# Once you create a PVC use it in a POD definition file by specifying the PVC Claim name under persistentVolumeClaim section in the volumes section like this:
# apiVersion: v1
# kind: Pod
# metadata:
#   name: mypod
# spec:
#   containers:
#     - name: myfrontend
#       image: nginx
#       volumeMounts:
#       - mountPath: "/var/www/html"
#         name: mypd
#   volumes:
#     - name: mypd
#       persistentVolumeClaim:
#         claimName: myclaim


# The same is true for ReplicaSets or Deployments. Add this to the pod template section of a Deployment on ReplicaSet.

# Reference URL: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#claims-as-volumes

#spec:
#  containers:
    # volumeMounts:
    # - name: localtime
    #   mountPath: /etc/localtime
  # volumes:
  #   - name: localtime
  #     hostPath:
  #       path: /usr/share/zoneinfo/Asia/Shanghai
  # volumes:
  # - name: log-volume
  #   persistentVolumeClaim:
  #     claimName: claim-log-1
  # restartPolicy: Always