version: 2
services:
  redis:
    image: redis
    networks:
      - back-end

  db:
    image: postgres:9.4
    networks:
      - back-end

  vote:
    build: ./vote
    networks:
      - back-end
    ports:
      - 5000:80
    depends_on:
      - redis      

  result:
    build: ./result
    networks:
      - back-end
      - front-end
    ports:
      - 5001:80

  worker:
    build: ./worker
    networks:
      - back-end
      - front-end

networks:
  front-end:
  back-end:
