apiVersion: v1
kind: ResourceQuota
metadata: 
  name: computer-quota
  namespace: dev

spec:
  hard:
    pods: "10"
    requirests.cpu: "4"
    request.memory: 5Gi
    limits.cpu: "10"
    limits.memory: 10Gi
